TYPO3:
  Neos:

    userInterface:
      requireJsPathMapping:
        'TYPO3.Neos.GoogleAnalytics/Inspector/Editors': 'resource://TYPO3.Neos.GoogleAnalytics/Public/Scripts/Inspector/Editors'

      translation:
        autoInclude:
          'TYPO3.Neos.GoogleAnalytics': ['NodeTypes/*']

    modules:
      administration:
        submodules:
          googleAnalytics:
            label: 'Analytics'
            controller: 'TYPO3\Neos\GoogleAnalytics\Controller\ConfigurationController'
            description: 'Google Analytics configuration'
            icon: 'icon-bar-chart icon-line-chart'
            privilegeTarget: 'TYPO3.Neos.GoogleAnalytics:Module.Administration.Configuration'

    typoScript:
      autoInclude:
        'TYPO3.Neos.GoogleAnalytics': TRUE

    GoogleAnalytics:

      authentication:
        # Application name for the consent screen
        applicationName: 'TYPO3 Neos'
        # "Client ID" of the OAuth 2.0 "Client ID for web application"
        clientId: ~
        # "Client Secret" of the OAuth 2.0 "Client ID for web application"
        clientSecret: ~
        # "API Key" of the Public API access credential "Key for server applications"
        developerKey: ~

      stats:
        uniquePageviewsPerDay:
          metrics: 'ga:uniquePageviews'
          dimensions: 'ga:date'
        basic:
          metrics: 'ga:pageviews,ga:uniquePageviews,ga:users'
        uniquePageviewsByUserType:
          metrics: 'ga:uniquePageviews'
          dimensions: 'ga:userType'
        uniquePageviewsByDeviceCategory:
          metrics: 'ga:uniquePageviews'
          dimensions: 'ga:deviceCategory'

      # Site specific settings
      sites: []
        ## All site specific settings are indexed by site node name
        #
        # neosdemotypo3org:
        #   trackingId: 'UA-XXXXX-YY'
        #   profileId: '12345678'
